app:
  name: here
greetings:
  name: World
  suffix: Nice to see you in '${app.name}'
important:
  stuff:
    - Chocolate
    - Milk
    - Buggers
logging:
  file: app.log
  level:
    org.springframework.web: DEBUG
---
spring:
  profiles: kuvaldis
greetings:
  name: Kuvaldis
app:
  name: The Spring Boot Play Application
---
spring:
  datasource:
    url: jdbc:h2:mem:spring-boot
    user: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop